### ISSUE TITLE
User unable to enter Agency during registration

### ISSUE THREAD

**Issue by lsoman** [on-site/grantzilla#139]
Issue:
Agency field disabled when entering registration information.
Note:Initially before entering any data Agency dropdown is enabled but after entering "Name", agency is disabled

Expected:
User should be allowed to select the "Agency" during registration

**Comment by joseph-ravenwolfe** [comment]
This is desired behavior, as it becomes disabled if the user belongs to the HIF organization. Closing for now. Please reopen if there is any further discussion on this.
