### ISSUE TITLE
Last Name should be on a 2nd line. 

### ISSUE THREAD

**Issue by mbatraski** [on-site/grantzilla#142]
The names of the applicant could be long 
It would be nice if we could have line1: !st name
Line2: last name
Line 3: Phone and email
Line 4: DOB and Veteran and Student status. 
Those fields are pretty short. 

<img width="1315" alt="screen shot 2016-01-28 at 12 39 42 pm" src="https://cloud.githubusercontent.com/assets/3477993/12658287/f1876dd2-c5bc-11e5-9364-13647fdd2e4e.png">

**Comment by dave5104** [comment]
I'll take a look at this page.
