### ISSUE TITLE
Print Application with All Uploaded Documents (5 pts)

### ISSUE THREAD

**Issue by lamplus** [on-site/grantzilla#304]
Print all uploaded documents when printing the application.

**Comment by scottjones** [comment]
Like make them all come out at once?  Does this involve stitching the documents together?

**Comment by lamplus** [comment]
Stitch together images and pdf documents.  Look into using https://github.com/boazsegev/combine_pdf to stitch together pdfs and look into using You can use RMagick's ImageList#write to create a pdf that stitches together uploaded images.

**Comment by lamplus** [comment]
Finished.
