### ISSUE TITLE
Need to add a port and host to database.yml

### ISSUE THREAD

**Issue by dave5104** [on-site/grantzilla#43]
In order to get my database connected to the application, I need to add this to `config/database.yml`:

```
default: &default
+  port: 5432
+  host: localhost
```

It'd be nice to not have to do that, since not everyone needs to do that in their environment.

**Comment by betesh** [comment]
Those are the defaults according to [source](https://github.com/rails/rails/blob/v4.2.5/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb#L53).  I'd be interested in knowing why you needed this before adding code for it.  It may be there's some wider environment issue at play, and adding this code would only be a partial solution.

**Comment by dave5104** [comment]
Hmm, removing the `port` line still leaves it working. For some reason seems that the host isn't defaulting to localhost.

**Comment by betesh** [comment]
Any way to figure out what host is defaulting to?

**Comment by dave5104** [comment]
Not sure what it was defaulting to, but my basic `psql` command in my terminal wasn't working. @josephjaber helped me get that fixed and now it works like a charm after reinstalling the `pg` gem.
