### ISSUE TITLE
Only allow creating a grant if you're logged in

### ISSUE THREAD

**Issue by scottjones** [on-site/grantzilla#56]
You shouldn't be able to create a grant unless you're logged in!
Also, please keep track of the user id who creates a grant.

**Comment by dennisbaskin** [comment]
I thought this was done already in #70, let me double check

**Comment by dennisbaskin** [comment]
@scottjones,  I see in your note you mention a separate item: "Also, please keep track of the user id who creates a grant." I am opening a separate ticket for that
