### ISSUE TITLE
User Management

### ISSUE THREAD

**Issue by lsoman** [on-site/grantzilla#72]
Issue:
Users are displayed as "User 1" and "User 2"

Expected:
-User 1 to be renamed as "Admin"/"Administrator"
-User 2 to be renamed as "Case Worker"

**Comment by dave5104** [comment]
It should actually be a list of users. It's meant to filter by the Case Worker column.

As the list of users grows, it should probably be limited to only when an agency is already filtered.

**Comment by joseph-ravenwolfe** [comment]
Resolved by @samerbuna in #146
